api:  
  build: .
  ports: 
    - 3000:3000
  links:
    - database
  environment:
    - DB_NAME=todos
    - DB_SERVER=database
    - PORT=3000

database:  
  image: mongo:latest
  command: mongod --smallfiles --quiet --logpath=/dev/null
